config/routes.rb
Rails.application.routes.draw do
  resources :article_collections
  resources :collection_tags
  resources :site_name_corrections
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "root#index"

  get "search" => "sentences#index"
  get "show_sentences_with_particle_and_verb" => "sentences#show_sentences_with_particle_and_verb"
  get "articles/:uuid", to: "articles#show", as: "article"
  get "articles/:uuid/:line_number", to: "articles#context", as: "article_context"
  get "articles", to: "articles#index"

  resource :token_analysis_manager do
    get :status
    post :start
    post :stop
  end

  namespace :collocations do
    scope controller: :nouns, path: :nouns, as: :nouns do
      get :index, path: "/"
      get :verbs
      get :adjectives
    end
  end

  namespace :stats do
    get :index, path: "/"
    get :total_articles
    get :total_sentences
    get :total_token_analyses
    get :sentence_analysis_ratio
    get :sentences_per_article
    get :tokens_per_sentence
    get :articles_by_site_name
    get :sentences_by_site_name
  end

  get "token_analysis_analyzer" => "token_analysis_analyzer#index"
end

app/models/article_collection.rb
# A collection of articles
class ArticleCollection < ApplicationRecord
  has_many :articles, dependent: :nullify
  has_many :article_collection_taggings, dependent: :destroy
  has_many :collection_tags, through: :article_collection_taggings

  validates :key, presence: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/article_collections_controller.rb
# Controller for ArticleCollection
class ArticleCollectionsController < ApplicationController
  layout "empty"

  before_action :set_article_collection, only: [:show, :edit, :update, :destroy]

  # GET /article_collections
  def index
    @article_collections = ArticleCollection.all
  end

  # GET /article_collections/1
  def show; end

  # GET /article_collections/new
  def new
    @article_collection = ArticleCollection.new
  end

  # GET /article_collections/1/edit
  def edit; end

  # POST /article_collections
  def create
    @article_collection = ArticleCollection.new(article_collection_params)

    respond_to do |format|
      if @article_collection.save
        format.html { redirect_to @article_collection, notice: t(".success") }
      else
        format.html { render :new, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /article_collections/1
  def update
    respond_to do |format|
      if @article_collection.update(article_collection_params)
        format.html do
          redirect_to @article_collection, notice: t(".success"), status: :see_other
        end
      else
        format.html { render :edit, status: :unprocessable_content }
      end
    end
  end

  # DELETE /article_collections/1
  def destroy
    @article_collection.destroy!

    respond_to do |format|
      format.html do
        redirect_to article_collections_path, notice: t(".success"),
                                              status: :see_other
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article_collection
    @article_collection = ArticleCollection.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def article_collection_params
    params.expect(article_collection: [:name, :key])
  end
end

app/views/article_collections/_article_collection.html.erb
<div id="<%= dom_id article_collection %>">
  <div>
    <strong>Name:</strong>
    <%= article_collection.name %>
  </div>

  <div>
    <strong>Key:</strong>
    <%= article_collection.key %>
  </div>

</div>

app/views/article_collections/_form.html.erb
<%= form_with(model: article_collection) do |form| %>
  <% if article_collection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article_collection.errors.count, "error") %> prohibited this article_collection from being saved:</h2>

      <ul>
        <% article_collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :key, style: "display: block" %>
    <%= form.text_field :key %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/article_collections/edit.html.erb
<% content_for :title, "Editing article collection" %>

<h1>Editing article collection</h1>

<%= render "form", article_collection: @article_collection %>

<br>

<div>
  <%= link_to "Show this article collection", @article_collection %> |
  <%= link_to "Back to article collections", article_collections_path %>
</div>

app/views/article_collections/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Article collections" %>

<h1>Article collections</h1>

<div id="article_collections">
  <% @article_collections.each do |article_collection| %>
    <%= render article_collection %>
    <p>
      <%= link_to "Show this article collection", article_collection %>
    </p>
  <% end %>
</div>

<%= link_to "New article collection", new_article_collection_path %>

app/views/article_collections/new.html.erb
<% content_for :title, "New article collection" %>

<h1>New article collection</h1>

<%= render "form", article_collection: @article_collection %>

<br>

<div>
  <%= link_to "Back to article collections", article_collections_path %>
</div>

app/views/article_collections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article_collection %>

<div>
  <%= link_to "Edit this article collection", edit_article_collection_path(@article_collection) %> |
  <%= link_to "Back to article collections", article_collections_path %>

  <%= button_to "Destroy this article collection", @article_collection, method: :delete %>
</div>